import Head from "next/head";
import { useTranslations } from "next-intl";
import { getI18nServerSideProps } from "@/shared/getI18nServerSideProps";
import { Footer } from "@/components/Footer";

export default function Home() {
  const t = useTranslations("HomePage");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>{t("title")}</main>
        <Footer />
      </div>
    </>
  );
}

export const getServerSideProps = getI18nServerSideProps;
